### ISSUE TITLE
Could you please add AS5047P SPI support or Macros?

### ISSUE THREAD

**Issue by taskx6004** [sosandroid/AMS_AS5048B#11]
Hi sosandroid,

Sir, would you have time to investigate how many functions could be reused in AS5047P to your library. They have almost identical registers i think, but minor different hardware capability setups.

**Comment by sosandroid** [comment]
Not sure on how I can help doing this. My lib is targeted to I2C bus.
The first idea is to add support for SPI in this lib.
But I lacks time those days
